[doctest] run with "--help" for options
===============================================================================
[doctest] test cases:      0 |      0 passed |      0 failed | 
[doctest] assertions:      0 |      0 passed |      0 failed |
[doctest] Status: SUCCESS!
Program code.
D:\doctest\examples\all_features\asserts_used_outside_of_tests.cpp(12): ERROR: FAST_CHECK_EQ( true, false ) is NOT correct!
  values: FAST_CHECK_EQ( true, false )
D:\doctest\examples\all_features\asserts_used_outside_of_tests.cpp(13): ERROR: FAST_CHECK_UNARY( false ) is NOT correct!
  values: FAST_CHECK_UNARY( false )
D:\doctest\examples\all_features\asserts_used_outside_of_tests.cpp(14): ERROR: FAST_CHECK_UNARY_FALSE( true ) is NOT correct!
  values: FAST_CHECK_UNARY_FALSE( true )
D:\doctest\examples\all_features\asserts_used_outside_of_tests.cpp(16): ERROR: CHECK_EQ( true, false ) is NOT correct!
  values: CHECK_EQ( true, false )
D:\doctest\examples\all_features\asserts_used_outside_of_tests.cpp(17): ERROR: CHECK_UNARY( false ) is NOT correct!
  values: CHECK_UNARY( false )
D:\doctest\examples\all_features\asserts_used_outside_of_tests.cpp(18): ERROR: CHECK_UNARY_FALSE( true ) is NOT correct!
  values: CHECK_UNARY_FALSE( true )
D:\doctest\examples\all_features\asserts_used_outside_of_tests.cpp(20): ERROR: CHECK( false ) is NOT correct!
  values: CHECK( false )
D:\doctest\examples\all_features\asserts_used_outside_of_tests.cpp(21): ERROR: an assert dealing with exceptions has failed!
